export const IPC_CHANNELS = {
  appGetState: "app:get-state",
  appGetMeta: "app:get-meta",
  appBootstrap: "app:bootstrap",
  appLaunchKiro: "app:launch-kiro",
  appOpenResource: "app:open-resource",
  appOpenPath: "app:open-path",
  diagnosticsExport: "diagnostics:export",
  diagnosticsExportFile: "diagnostics:export-file",
  diagnosticsExportZip: "diagnostics:export-zip",
  diagnosticsClearHistory: "diagnostics:clear-history",
  diagnosticsSelectBundle: "diagnostics:select-bundle",
  diagnosticsDeleteBundle: "diagnostics:delete-bundle",
  proxyStart: "proxy:start",
  proxyStop: "proxy:stop",
  proxyRestart: "proxy:restart",
  proxySetEnabled: "proxy:set-enabled",
  proxySetAutoApplyOnLaunch: "proxy:set-auto-apply-on-launch",
  providerSave: "provider:save",
  providerTest: "provider:test",
  providerFetchModels: "provider:fetch-models",
  kiroDetect: "kiro:detect",
  kiroApplyRouting: "kiro:apply-routing",
  kiroDiagnose: "kiro:diagnose",
  kiroRestore: "kiro:restore",
  logsList: "logs:list",
  playgroundSend: "playground:send"
};
